/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server_Download;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;

public class DownloadScreen4 extends javax.swing.JFrame {
    
    private Image originalImage;
    private String ans = "";
    private Color H;
    Color h = new Color(51, 51, 255);
    private Color D;
    Color d = new Color(255, 255, 255);

    public DownloadScreen4() {
        initComponents(); // I summon thee
        this.setResizable(false); // Lock diminutive Form

        // I cast a protective barrier against the vanished
        if (image1.getIcon() != null && image1.getIcon() instanceof ImageIcon) {
            originalImage = ((ImageIcon) image1.getIcon()).getImage();
        } else {
            System.out.println("⚠️ Warning: image1 icon is null or not an ImageIcon!");
        }

        // I cast binding body morph when one is not vanished
        if (originalImage != null) {
            image1.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    int labelWidth = image1.getWidth();
                    int labelHeight = image1.getHeight();

                    if (labelWidth > 0 && labelHeight > 0) {
                        int newHeight = getHeightFromWidth(originalImage, labelWidth);
                        Image scaledImage = originalImage.getScaledInstance(labelWidth, newHeight, Image.SCALE_SMOOTH);
                        image1.setIcon(new ImageIcon(scaledImage));
                        image1.repaint();
                    }
                }
            });

            // Now resize my creation!
            int initialWidth = image1.getWidth();
            int initialHeight = image1.getHeight();
            if (initialWidth > 0 && initialHeight > 0) {
                int newHeight = getHeightFromWidth(originalImage, initialWidth);
                Image scaledImage = originalImage.getScaledInstance(initialWidth, newHeight, Image.SCALE_SMOOTH);
                image1.setIcon(new ImageIcon(scaledImage));
                image1.repaint();
            }
        }
    }

    private int getHeightFromWidth(Image image, int desiredWidth) {
        int originalWidth = image.getWidth(null);
        int originalHeight = image.getHeight(null);

        // Debugging: Check original image dimensions
//        System.out.println("Original Image Dimensions: Width = " + originalWidth + " Height = " + originalHeight);

        return (int) (((double) desiredWidth / originalWidth) * originalHeight);
    }
    
    
    
    String ans1(String ans)
    {
//        String a = ans;
//        System.out.println("" + a);
//        System.out.println(""+ans);
        return ans;
    }













   
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JPanel();
        Button2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        check = new javax.swing.JCheckBox();
        image1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(11, 11, 69));
        jPanel1.setMinimumSize(new java.awt.Dimension(1320, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1320, 640));
        jPanel1.setLayout(null);

        Button1.setBackground(new java.awt.Color(255, 255, 255));
        Button1.setRequestFocusEnabled(false);
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
        });
        Button1.setLayout(null);

        Button2.setBackground(new java.awt.Color(255, 255, 255));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button2MouseExited(evt);
            }
        });
        Button2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Next");
        Button2.add(jLabel2);
        jLabel2.setBounds(20, 0, 50, 25);

        Button1.add(Button2);
        Button2.setBounds(8, 7, 90, 25);

        jPanel1.add(Button1);
        Button1.setBounds(830, 445, 105, 38);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        check.setBackground(new java.awt.Color(255, 255, 255));
        check.setText("I accept the license terms");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel3.add(check);
        check.setBounds(0, 0, 180, 25);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(265, 413, 280, 40);

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s4.png"))); // NOI18N
        jPanel1.add(image1);
        image1.setBounds(0, 0, 1170, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseEntered
//        Button1.setBackground(h);
    }//GEN-LAST:event_Button1MouseEntered

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseExited
//        Button1.setBackground(d);
    }//GEN-LAST:event_Button1MouseExited

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
    DownloadScreen2 ds2 = new DownloadScreen2();
    ds2.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Button1MouseClicked

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        boolean isSelected = check.isSelected();

    if (isSelected) 
    {      
        ans = "Yes"; //Before this was Sting ans = "Yes", this made it a local variable, not class-level
        ans1(ans); 
    } else 
    {      
        ans = "No"; //Before this was Sting ans = "No", this made it a local variable, not class-level
        ans1(ans);
    }
    }//GEN-LAST:event_checkActionPerformed

    private void Button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseEntered
        Button2.setBackground(h);
    }//GEN-LAST:event_Button2MouseEntered

    private void Button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseExited
        Button2.setBackground(d);
    }//GEN-LAST:event_Button2MouseExited

    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseClicked
        ans1(ans);
        System.out.println("this is ans: " + ans);

        if (ans.equals("Yes")) 
        {
            DownloadScreen5 ds5 = new DownloadScreen5();
            ds5.setVisible(true);
            this.dispose();
        } else if (!ans.equals("Yes")) 
        {
            JOptionPane.showMessageDialog(null, "Wrong Option bud :)");
        }
    }//GEN-LAST:event_Button2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadScreen4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button1;
    private javax.swing.JPanel Button2;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
