/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server_Download;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;

public class DownloadScreen3 extends javax.swing.JFrame {
    
    private Image originalImage;   
    private String ans = " ";
    private Color H;
    Color h = new Color(51, 51, 255);
    private Color D;
    Color d = new Color(255,255,255);

    public DownloadScreen3() {
        initComponents(); // I summon thee
        this.setResizable(false); // Lock diminutive Form

        // I cast a protective barrier against the vanished
        if (image1.getIcon() != null && image1.getIcon() instanceof ImageIcon) {
            originalImage = ((ImageIcon) image1.getIcon()).getImage();
        } else {
            System.out.println("⚠️ Warning: image1 icon is null or not an ImageIcon!");
        }

        // I cast binding body morph when one is not vanished
        if (originalImage != null) {
            image1.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    int labelWidth = image1.getWidth();
                    int labelHeight = image1.getHeight();

                    if (labelWidth > 0 && labelHeight > 0) {
                        int newHeight = getHeightFromWidth(originalImage, labelWidth);
                        Image scaledImage = originalImage.getScaledInstance(labelWidth, newHeight, Image.SCALE_SMOOTH);
                        image1.setIcon(new ImageIcon(scaledImage));
                        image1.repaint();
                    }
                }
            });

            // Now resize my creation!
            int initialWidth = image1.getWidth();
            int initialHeight = image1.getHeight();
            if (initialWidth > 0 && initialHeight > 0) {
                int newHeight = getHeightFromWidth(originalImage, initialWidth);
                Image scaledImage = originalImage.getScaledInstance(initialWidth, newHeight, Image.SCALE_SMOOTH);
                image1.setIcon(new ImageIcon(scaledImage));
                image1.repaint();
            }
        }
    }

    private int getHeightFromWidth(Image image, int desiredWidth) {
        int originalWidth = image.getWidth(null);
        int originalHeight = image.getHeight(null);

        // Debugging: Check original image dimensions
//        System.out.println("Original Image Dimensions: Width = " + originalWidth + " Height = " + originalHeight);
        return (int) (((double) desiredWidth / originalWidth) * originalHeight);
    }
    
    
    String ans1(String ans)
    {
//        String a = ans;
//        System.out.println("" + a);
//        System.out.println(""+ans);
        return ans;
    }













   
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RightAns = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RightAns1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RightAns2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RightAns3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(11, 11, 69));
        jPanel1.setMinimumSize(new java.awt.Dimension(1320, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1320, 640));
        jPanel1.setLayout(null);

        Button1.setBackground(new java.awt.Color(255, 255, 255));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
        });
        Button1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Next");
        Button1.add(jLabel1);
        jLabel1.setBounds(20, 0, 50, 20);

        jPanel1.add(Button1);
        Button1.setBounds(839, 455, 90, 20);

        RightAns.setBackground(new java.awt.Color(255, 255, 255));
        RightAns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RightAnsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RightAnsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RightAnsMouseExited(evt);
            }
        });
        RightAns.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Windows Server 2016 Standard (Desktop Experience)");
        RightAns.add(jLabel2);
        jLabel2.setBounds(1, 0, 381, 13);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("x64");
        RightAns.add(jLabel3);
        jLabel3.setBounds(385, 0, 100, 13);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("11/21/2016");
        RightAns.add(jLabel4);
        jLabel4.setBounds(492, 0, 110, 13);

        jPanel1.add(RightAns);
        RightAns.setBounds(279, 208, 594, 13);

        RightAns1.setBackground(new java.awt.Color(255, 255, 255));
        RightAns1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RightAns1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RightAns1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RightAns1MouseExited(evt);
            }
        });
        RightAns1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Windows Server 2016 Datacenter");
        RightAns1.add(jLabel5);
        jLabel5.setBounds(1, 0, 381, 13);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("x64");
        RightAns1.add(jLabel6);
        jLabel6.setBounds(385, 0, 100, 13);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("11/21/2016");
        RightAns1.add(jLabel7);
        jLabel7.setBounds(492, 0, 110, 13);

        jPanel1.add(RightAns1);
        RightAns1.setBounds(279, 221, 594, 13);

        RightAns2.setBackground(new java.awt.Color(255, 255, 255));
        RightAns2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RightAns2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RightAns2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RightAns2MouseExited(evt);
            }
        });
        RightAns2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Windows Server 2016 Datacenter (Desktop Experience)");
        RightAns2.add(jLabel8);
        jLabel8.setBounds(1, 0, 381, 13);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("x64");
        RightAns2.add(jLabel9);
        jLabel9.setBounds(385, 0, 100, 13);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("11/21/2016");
        RightAns2.add(jLabel10);
        jLabel10.setBounds(492, 0, 110, 13);

        jPanel1.add(RightAns2);
        RightAns2.setBounds(279, 235, 594, 13);

        RightAns3.setBackground(new java.awt.Color(255, 255, 255));
        RightAns3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RightAns3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RightAns3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RightAns3MouseExited(evt);
            }
        });
        RightAns3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Windows Server 2016 Standard");
        RightAns3.add(jLabel11);
        jLabel11.setBounds(1, 0, 381, 13);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("x64");
        RightAns3.add(jLabel12);
        jLabel12.setBounds(385, 0, 100, 13);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("11/21/2016");
        RightAns3.add(jLabel13);
        jLabel13.setBounds(492, 0, 110, 13);

        jPanel1.add(RightAns3);
        RightAns3.setBounds(279, 194, 594, 13);

        image1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s3.png"))); // NOI18N
        image1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image1MouseClicked(evt);
            }
        });
        jPanel1.add(image1);
        image1.setBounds(0, 0, 1170, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseEntered
        Button1.setBackground(h);
    }//GEN-LAST:event_Button1MouseEntered

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseExited
        Button1.setBackground(d);
    }//GEN-LAST:event_Button1MouseExited

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        
        ans1(ans);
        System.out.println("this is ans: " + ans);

        if (ans.equals("Yes")) {
            DownloadScreen4 ds4 = new DownloadScreen4();
            ds4.setVisible(true);
            this.dispose();
        } else if (!ans.equals("Yes")) {
            ans = " ";
            JOptionPane.showMessageDialog(null, "Wrong Option bud :)");
            RightAns.setBackground(d);
            RightAns1.setBackground(d);
            RightAns2.setBackground(d);
            RightAns3.setBackground(d);
            
            
        }
    }//GEN-LAST:event_Button1MouseClicked

    private void RightAnsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAnsMouseEntered
        RightAns.setBackground(h);
    }//GEN-LAST:event_RightAnsMouseEntered

    private void RightAnsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAnsMouseExited
        if (!ans.equals("Yes")) {
            RightAns.setBackground(d);
        } else if (ans.equals("Yes") || !ans.equals(" ")) {
            RightAns.setBackground(h);
        }
    }//GEN-LAST:event_RightAnsMouseExited

    private void RightAnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAnsMouseClicked
        ans = "Yes"; //Before this was Sting ans = "Yes", this made it a local variable, not class-level
        ans1(ans);
        
        
    }//GEN-LAST:event_RightAnsMouseClicked

    private void image1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1MouseClicked
//        String ans = "No";
//        System.out.println(""+ans);
//        JOptionPane.showMessageDialog(null, "Wrong Option bud :)");
//        ans1(ans);

    }//GEN-LAST:event_image1MouseClicked

    private void RightAns1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns1MouseClicked
//        JOptionPane.showMessageDialog(null, "Wrong Option Bud :D, Try again");
        ans = "1"; //Before this was Sting ans = "No", this made it a local variable, not class-level
        ans1(ans);
        
    }//GEN-LAST:event_RightAns1MouseClicked

    private void RightAns1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns1MouseEntered
        RightAns1.setBackground(h);
    }//GEN-LAST:event_RightAns1MouseEntered

    private void RightAns1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns1MouseExited
        if (!ans.equals("1")) {
            RightAns1.setBackground(d);
        } else if (ans.equals("1") || !ans.equals(" ")) {
            RightAns1.setBackground(h);
        }
    }//GEN-LAST:event_RightAns1MouseExited

    private void RightAns2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns2MouseClicked
//        JOptionPane.showMessageDialog(null, "Wrong Option Bud :D, Try again");
        ans = "2"; //Before this was Sting ans = "No", this made it a local variable, not class-level
        ans1(ans);
        
    }//GEN-LAST:event_RightAns2MouseClicked

    private void RightAns2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns2MouseEntered
        RightAns2.setBackground(h);
    }//GEN-LAST:event_RightAns2MouseEntered

    private void RightAns2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns2MouseExited
        if (!ans.equals("2")) {
            RightAns2.setBackground(d);
        } else if (ans.equals("2") || !ans.equals(" ")) {
            RightAns2.setBackground(h);
        }
    }//GEN-LAST:event_RightAns2MouseExited

    private void RightAns3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns3MouseClicked
//        JOptionPane.showMessageDialog(null, "Wrong Option Bud :D, Try again");
        ans = "3"; //Before this was Sting ans = "No", this made it a local variable, not class-level
        ans1(ans);
        
    }//GEN-LAST:event_RightAns3MouseClicked

    private void RightAns3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns3MouseEntered
        RightAns3.setBackground(h);
    }//GEN-LAST:event_RightAns3MouseEntered

    private void RightAns3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightAns3MouseExited
        if (!ans.equals("3")) {
            RightAns3.setBackground(d);
        } else if (ans.equals("3")|| !ans.equals(" ")) {
            RightAns3.setBackground(h);
        }
        System.out.println("Ans: "+ans);
    }//GEN-LAST:event_RightAns3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadScreen3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button1;
    private javax.swing.JPanel RightAns;
    private javax.swing.JPanel RightAns1;
    private javax.swing.JPanel RightAns2;
    private javax.swing.JPanel RightAns3;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
